name: std
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - blas=2.305=openblas
  - blas-devel=3.11.0=5_ha590de0_openblas
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2026.1.4=h4c7d964_0
  - cairo=1.18.4=h477c42c_1
  - contourpy=1.3.2=py310hc19bc0b_0
  - cycler=0.12.1=pyhcf101f3_2
  - double-conversion=3.4.0=hac47afa_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py310hdb0e946_0
  - freetype=2.14.1=h57928b3_0
  - graphite2=1.3.14=hac47afa_2
  - harfbuzz=12.2.0=h5a1b470_1
  - icu=78.1=h637d24d_0
  - kiwisolver=1.4.9=py310h1e1005b_2
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250512.1=cxx17_habfad5f_0
  - libblas=3.11.0=5_h0adab6e_openblas
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.11.0=5_h2a8eebe_openblas
  - libclang13=21.1.7=default_ha2db4b5_2
  - libdeflate=1.25=h51727cc_0
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h8ee18e1_16
  - libglib=2.86.3=h0c9aed9_0
  - libgomp=15.2.0=h8ee18e1_16
  - libhwloc=2.12.1=default_h4379cf1_1003
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.11.0=5_hd232482_openblas
  - liblapacke=3.11.0=5_hbb0e6ff_openblas
  - liblzma=5.8.1=h2466b09_2
  - libopenblas=0.3.30=pthreads_h877e47f_4
  - libpng=1.6.53=h7351971_0
  - libprotobuf=6.31.1=hdcda5b4_4
  - libsqlite=3.51.1=hf5d6505_0
  - libtiff=4.7.1=h8f73337_1
  - libvulkan-loader=1.4.328.1=h477610d_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.15.1=h779ef1b_1
  - libxml2-16=2.15.1=h3cfd58e_1
  - libxslt=1.1.43=h0fbe4c1_1
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.8=h4fa8253_0
  - matplotlib=3.10.8=py310h5588dad_0
  - matplotlib-base=3.10.8=py310h0bdd906_0
  - mkl=2025.3.0=hac47afa_454
  - ml_dtypes=0.5.4=np2py310h7578f05_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - nomkl=3.0=0
  - numpy=1.26.0=py310hf667824_0
  - onnx=1.20.0=py310hb14096e_1
  - openblas=0.3.30=pthreads_h4a7f399_4
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=3.6.0=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - pcre2=10.47=hd2b5f0e_0
  - pillow=12.0.0=py310h712baa7_2
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h5112557_1
  - protobuf=6.31.1=py310h81b7714_2
  - pthread-stubs=0.4=h0e40799_1002
  - pyparsing=3.3.1=pyhcf101f3_0
  - pyside6=6.10.1=py310h96c60bd_0
  - python=3.10.19=hc20f281_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=8_cp310
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.10.1=h68b6638_4
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - tbb=2022.3.0=hd094cb3_1
  - tk=8.6.13=h2c6b04d_3
  - tornado=6.5.4=py310h29418f3_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=h8577fbf_0
  - ucrt=10.0.26100.0=h57928b3_0
  - unicodedata2=17.0.0=py310h29418f3_1
  - vc=14.3=h2b53caa_33
  - vc14_runtime=14.44.35208=h818238b_33
  - vcomp14=14.44.35208=h818238b_33
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - zlib-ng=2.3.2=h0261ad2_1
  - zstd=1.5.7=h534d264_6
  - pip:
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - filelock==3.20.0
      - idna==3.4
      - jinja2==3.1.6
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.4.2
      - requests==2.28.1
      - sympy==1.14.0
      - torch==2.0.1+cu118
      - torchaudio==2.0.2+cu118
      - torchvision==0.15.2+cu118
      - urllib3==1.26.13
prefix: C:\Users\constintnb\.conda\envs\std
